"use client";
import { useState } from "react";
import { BrainCircuit,BriefcaseBusiness,CircleUserRound,Mail,Sparkles,UsersRound,X } from "lucide-react";
import { MagicalWorld } from "./MagicalWorld";
type Portal={id:string;label:string;icon:typeof Sparkles;title:string;body:string;action?:string;href?:string};
const portals:Portal[]=[
  {id:"world",label:"Enter world",icon:Sparkles,title:"Fly Through My World",body:"Guide a tiny knowledge sprite through a world shaped by data, AI, projects, and community.",action:"Start exploring"},
  {id:"projects",label:"Projects",icon:BriefcaseBusiness,title:"Ideas made tangible",body:"Green certificate analytics, knowledge agents, data engineering education, and practical AI workflows."},
  {id:"skills",label:"Skills",icon:BrainCircuit,title:"Data, cloud, and AI",body:"Python, SQL, PySpark, Azure, AWS, Databricks, Snowflake, Power BI, enterprise platforms, governance, and AI-assisted engineering."},
  {id:"community",label:"Make AI Practical",icon:UsersRound,title:"Making AI useful",body:"As a Board Member, I support strategic initiatives, workshops, community learning, and practical experiences that turn AI knowledge into outcomes."},
  {id:"about",label:"About Yangyang",icon:CircleUserRound,title:"Curious by design",body:"AI-Powered Data Engineer, community builder, teacher, traveller, pottery learner, reader, gamer, and collector of interesting ideas."},
  {id:"contact",label:"Say hello",icon:Mail,title:"Let’s build something useful",body:"The easiest way to start a conversation is by email.",href:"mailto:hello@yangyangcai.me"},
];
export function MagicalStart(){
  const[active,setActive]=useState<Portal|null>(null);const[exploring,setExploring]=useState(false);
  if(exploring)return <MagicalWorld/>;
  return <main className="study-desktop"><div className="study-stars" aria-hidden/><div className="study-moon" aria-hidden/><div className="study-mountains" aria-hidden/><div className="study-desk" aria-hidden><i/><i/><i/></div><header className="study-topbar"><div><span className="study-sigil">YC</span><strong>Yangyang&apos;s magical study</strong></div><span>Data · AI · Energy · Creativity</span></header><section className="study-welcome"><p>Welcome, traveller</p><h1>A small world of<br/><em>ideas in motion.</em></h1><span>Open a portal to begin.</span></section><nav className="study-portals" aria-label="Portfolio portals">{portals.map(portal=>{const Icon=portal.icon;return <button key={portal.id} onClick={()=>setActive(portal)}><span><Icon size={25}/></span><b>{portal.label}</b></button>})}</nav><button className="study-sprite" onClick={()=>setExploring(true)} aria-label="Follow the flying sprite into the world"><i/><i/><i/><span>follow me</span></button><footer className="study-dock"><button onClick={()=>setActive(portals[0])}><Sparkles size={17}/> Explore</button><button onClick={()=>setActive(portals[1])}><BriefcaseBusiness size={17}/> Work</button><button onClick={()=>setActive(portals[5])}><Mail size={17}/> Contact</button></footer>{active&&<div className="study-window-layer" onMouseDown={event=>event.target===event.currentTarget&&setActive(null)}><article className="study-window" role="dialog" aria-modal="true" aria-labelledby="study-window-title"><header><span>✦ knowledge window</span><button onClick={()=>setActive(null)} aria-label="Close window"><X size={18}/></button></header><div><p className="world-eyebrow">Yangyang Cai</p><h2 id="study-window-title">{active.title}</h2><p>{active.body}</p>{active.id==="world"&&<button className="world-primary-button" onClick={()=>setExploring(true)}>{active.action} →</button>}{active.href&&<a className="world-primary-button" href={active.href}>Send an email →</a>}</div></article></div>}</main>;
}
