"use client";
import Image, { type StaticImageData } from "next/image";
import { useEffect,useState } from "react";
import { Archive,BookOpen,BriefcaseBusiness,CalendarDays,Compass,ExternalLink,Flower2,Gamepad2,Globe2,GraduationCap,Lightbulb,Presentation,Store,Link as LinkIcon,MapPin,Network,PartyPopper,Plane,MapPinned,Send,Sparkles,Star,Terminal,Wrench,X } from "lucide-react";
import { navigation,projects,type DesktopSection } from "@/content/desktop";
import characterImage from "@/assets/web/yangyang-character.webp";
import aboutCharacter from "@/assets/web/character-about.png";
import workCharacter from "@/assets/web/character-work.png";
import communityCharacter from "@/assets/web/character-community.png";
import booksCharacter from "@/assets/web/character-books.png";
import funCharacter from "@/assets/web/character-fun.png";
import contactCharacter from "@/assets/web/character-contact.png";
import communityImage from "@/assets/web/ai_event.webp";
import mercyBookImage from "@/assets/仁慈的关系.jpeg";
import nexusBookImage from "@/assets/智人之上.jpg";
import alchemistBookImage from "@/assets/牧羊少年奇幻之旅.jpg";
import potteryOneImage from "@/assets/web/pottery_1.webp";
import potteryTwoImage from "@/assets/web/pottery_2.webp";
import potteryThreeImage from "@/assets/web/pottery_3.webp";
import splitFictionImage from "@/assets/Split Fiction.png";
import itTakesTwoImage from "@/assets/it_takes_two.png";
import hogwartsLegacyImage from "@/assets/hogwarts_legacy.png";

const navIcons={about:Compass,work:Archive,community:Network,books:BookOpen,fun:PartyPopper,contact:Send};
type Language="en"|"zh";
const tr=(language:Language,en:string,zh:string)=>language==="zh"?zh:en;
const characterPoses:Record<DesktopSection,StaticImageData>={overview:characterImage,about:aboutCharacter,work:workCharacter,community:communityCharacter,books:booksCharacter,fun:funCharacter,contact:contactCharacter};

export function DesktopPortfolio(){
  const[active,setActive]=useState<DesktopSection>("overview");
  const[language,setLanguage]=useState<Language>("en");
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setActive("overview")};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  return <main className="desktop-shell" onPointerDown={(event)=>{if(active!=="overview"&&event.target===event.currentTarget)setActive("overview")}}>
    <div className="desktop-noise" aria-hidden/>
    <div className="window-stage">
    <section className={`desktop-window ${active==="overview"?"overview-window":"section-window"}`} aria-label={active==="overview"?"Portfolio overview":undefined} role={active==="overview"?undefined:"dialog"} aria-modal={active==="overview"?undefined:true}>
      <WindowBar title={windowTitle(active)}/>
      {active==="overview"&&<Overview onOpen={setActive} language={language} onLanguageChange={setLanguage}/>} {active==="about"&&<About language={language}/>} {active==="work"&&<Work language={language}/>} {active==="community"&&<Community language={language}/>} {active==="books"&&<Books language={language}/>} {active==="fun"&&<Fun language={language}/>} {active==="contact"&&<Contact language={language}/>}
      {active==="overview"&&<div className="window-status"><span><i/> Ready</span><span><i className="amber-dot"/> Creative mode</span><span className="status-right">&#10019; Optimized</span></div>}
    </section>
    <Character key={active} active={active}/>
    {active!=="overview"&&<button className="desktop-floating-close" onClick={()=>setActive("overview")} aria-label={`Close ${active} window`}><span className="sunflower-close" aria-hidden="true"><Flower2/><X/></span></button>}
    </div>
    <footer className="desktop-footer"><a href="https://www.linkedin.com" target="_blank" rel="noreferrer"><LinkIcon size={15}/> LinkedIn</a><span>&copy; 2026 Yangyang Cai · {language==="zh"?"中文版":"English"}</span></footer>
  </main>;
}

function WindowBar({title}:{title:string}){return <header className="window-bar"><span/><b>{title}</b><span/></header>}

function Character({active}:{active:DesktopSection}){const[greeting,setGreeting]=useState(false);return <button className={`desktop-character character-${active}`} onClick={()=>setGreeting(value=>!value)} aria-label="Say hello to Yangyang">{greeting&&<span className="character-greeting" role="status">Hi!</span>}<Image src={characterPoses[active]} alt={`Yangyang character for ${active}`} width={393} height={373} priority/></button>}

function Overview({onOpen,language,onLanguageChange}:{onOpen:(section:DesktopSection)=>void;language:Language;onLanguageChange:(language:Language)=>void}){return <div className="overview-content"><div className="language-switch" role="group" aria-label="Language"><button className={language==="en"?"active":""} onClick={()=>onLanguageChange("en")}>EN</button><button className={language==="zh"?"active":""} onClick={()=>onLanguageChange("zh")}>中文</button></div><h1>{tr(language,"Welcome to Yangyang's World","欢迎来到 Yangyang 的世界")}</h1><nav className="desktop-nav" aria-label={tr(language,"Portfolio sections","作品集栏目")}>{navigation.map(item=>{const Icon=navIcons[item.id];return <button key={item.id} onClick={()=>onOpen(item.id)}><span className={`nav-icon ${item.tone}`}><Icon size={24}/></span><b>{language==="zh"?item.labelZh:item.label}</b></button>})}</nav></div>}

function About({language}:{language:Language}){return <div className="window-page about-page"><p className="page-pill">{tr(language,"Professional profile","职业简介")}</p><h2>{tr(language,"Building the bridge between","连接")}<br/><em>{tr(language,"Data","数据")}</em> {tr(language,"and","与")} <strong>{tr(language,"Intelligence.","智能。")}</strong></h2><p className="page-lead">{tr(language,"Based in Melbourne, I am an AI-Powered Data Engineer dedicated to crafting robust data and AI solutions that solve real-world problems. I see data as more than numbers—it is the narrative of our digital lives, waiting for the right architecture to speak clearly.","我常驻墨尔本，是一名 AI 驱动的数据工程师，专注于打造稳健的数据与人工智能解决方案，解决真实世界的问题。对我而言，数据不仅是数字，更是数字生活的故事，等待合适的架构让它清晰表达。")}</p><h3>{tr(language,"Working style","工作方式")}</h3><div className="style-chips"><span><Wrench size={15}/>{tr(language,"Practical","务实")}</span><span><Terminal size={15}/>{tr(language,"Technical","技术导向")}</span><span><Lightbulb size={15}/>{tr(language,"Curious","保持好奇")}</span></div><hr/><section className="beyond-work"><p className="page-pill">{tr(language,"Beyond the work","工作之外")}</p><h3>{tr(language,"Curious by default.","天生好奇。")}</h3><p>{tr(language,"My favourite kind of downtime still involves a little discovery, imagination, or an unexpected side quest.","我喜欢在休息时间探索新事物、发挥想象力，或开启一段意想不到的支线任务。")}</p><div className="beyond-grid"><article><span className="interest-icon game"><Gamepad2/></span><b>{tr(language,"Video games","电子游戏")}</b><small>{tr(language,"Co-op adventures, magical worlds, and solving problems with better graphics.","合作冒险、魔法世界，以及画面更精彩的问题解决体验。")}</small></article><article><span className="interest-icon books"><BookOpen/></span><b>{tr(language,"Reading books","阅读")}</b><small>{tr(language,"Fantasy, new perspectives, and ideas that stay with me after the last page.","奇幻故事、新视角，以及合上书后依然留在心里的想法。")}</small></article><article><span className="interest-icon explore"><Sparkles/></span><b>{tr(language,"Trying new things","尝试新事物")}</b><small>{tr(language,"New crafts, unfamiliar places, and saying yes to the next small adventure.","新手艺、陌生的地方，以及勇敢接受下一次小冒险。")}</small></article></div></section></div>}

function Work({language}:{language:Language}){const ProjectIcons=[BriefcaseBusiness,Presentation,GraduationCap,Store];return <div className="window-page work-page"><h2>{tr(language,"Data Lover. Practical Builder.","热爱数据，也热衷把想法变成现实。")}</h2><p className="page-lead">{tr(language,"From reliable data platforms to shared learning and hands-on ideas—this is where curiosity turns into something useful.","从可靠的数据平台，到知识分享与亲手实践，这里记录着好奇心如何变成真正有用的成果。")}</p><div className="project-grid">{projects.map((project,index)=>{const Icon=ProjectIcons[index];const title=language==="zh"?project.titleZh:project.title;return <article key={project.title}><div className={`project-icon ${project.tone}`}><Icon/></div>{project.href?<a className="card-link" href={project.href} target={project.href.startsWith("http")?"_blank":undefined} rel={project.href.startsWith("http")?"noreferrer":undefined} aria-label={`Visit ${project.title}`}><ExternalLink size={17}/></a>:<ExternalLink className="card-link muted-link" size={17}/>}<h3>{title}</h3><p>{language==="zh"?project.descriptionZh:project.description}</p>{project.href&&<a className="project-visit" href={project.href} target={project.href.startsWith("http")?"_blank":undefined} rel={project.href.startsWith("http")?"noreferrer":undefined}>{language==="zh"?(project.linkLabelZh??title):(project.linkLabel??`Visit ${project.title}`)} <ExternalLink size={14}/></a>}<div>{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>})}</div><div className="work-status"><span>{tr(language,"4 projects selected","已选择 4 个项目")}</span><span><i/>{tr(language,"Synced","已同步")}</span><span>{tr(language,"Last updated: recently","最近更新")}</span></div></div>}

function Community({language}:{language:Language}){return <div className="window-page community-page"><div className="community-copy"><p className="page-pill">{tr(language,"Hands-on intensive","动手实践")}</p><h2>{tr(language,"Make AI practical.","让 AI 落地。")}<br/>{tr(language,"Make learning useful.","让学习有用。")}</h2><p className="page-lead">{tr(language,"As a Board Member of Make AI Practical, I support accessible workshops, strategic initiatives, and community experiences that help people turn AI knowledge into real outcomes.","作为 Make AI Practical 的董事会成员，我支持易于参与的工作坊、战略项目与社区活动，帮助大家把 AI 知识转化为真实成果。")}</p><p className="community-manifesto">{tr(language,"Together with a group of friends, I’m working to make","我和一群朋友一起，努力实现")} <strong>Real AI, Real Life, Real Connection.</strong></p><div className="event-facts"><span><CalendarDays/><small>{tr(language,"What","内容")}</small>{tr(language,"Knowledge Agent workshops","知识智能体工作坊")}</span><span><MapPin/><small>{tr(language,"Where","地点")}</small>{tr(language,"Melbourne & online","墨尔本及线上")}</span></div><div className="community-actions"><a className="solid-button" href="https://www.makeaipractical.com.au/" target="_blank" rel="noreferrer"><Globe2 size={17}/>{tr(language,"Visit website","访问官网")}</a><a className="outline-button" href="https://www.linkedin.com/company/make-ai-practical" target="_blank" rel="noreferrer"><LinkIcon size={17}/> LinkedIn</a><a className="eventbrite-button" href="https://www.eventbrite.com.au/e/stop-taking-notes-only-build-a-personal-knowledge-agent-in-3-hours-tickets-1989461171920" target="_blank" rel="noreferrer"><CalendarDays size={17}/>{tr(language,"Book on Eventbrite","在 Eventbrite 订票")}</a></div></div><aside className="curriculum-card"><Image src={communityImage} alt="Make AI Practical Knowledge Agent workshop event post" sizes="(max-width: 760px) 100vw, 36vw"/><h3>{tr(language,"Workshop curriculum","工作坊内容")}</h3><ul><li>{tr(language,"Knowledge graph foundations","知识图谱基础")}</li><li>{tr(language,"Practical AI workflows","实用 AI 工作流")}</li><li>{tr(language,"Custom RAG implementation","定制 RAG 实现")}</li><li>{tr(language,"Turning learning into outcomes","把学习转化为成果")}</li></ul></aside></div>}

function Books({language}:{language:Language}){return <div className="window-page books-page"><div className="book-focus"><Image src={mercyBookImage} alt="A current book from Yangyang's reading shelf" width={320} height={430}/><div><p className="page-pill">{tr(language,"Current focus","正在阅读")}</p><h2>{tr(language,"Relations of Grace","仁慈的关系")}</h2><p className="book-author">{tr(language,"László Krasznahorkai","László Krasznahorkai · 克拉斯诺霍尔卡伊・拉斯洛")}</p><OnlineRating score="3.66/5" source="Goodreads" href="https://www.goodreads.com/book/show/12938581-kegyelmi-viszonyok"/><blockquote>{tr(language,"Reading is how I borrow another person&apos;s mental model—and test it against my own.","阅读让我借用他人的思维模型，并用自己的经验去检验。")}</blockquote></div></div><section className="book-addition nexus-book"><Image className="book-cover-image" src={nexusBookImage} alt={tr(language,"Nexus book cover","《智人之上》封面")} width={320} height={430}/><div className="book-addition-copy"><p className="page-pill">{tr(language,"Current focus","正在阅读")}</p><h3>{tr(language,"Nexus","智人之上")}</h3><p className="book-author">{tr(language,"Yuval Noah Harari","Yuval Noah Harari · 尤瓦尔·赫拉利")}</p><p className="book-subtitle">{tr(language,"A Brief History of Information Networks from the Stone Age to AI","从石器时代到AI时代的信息网络简史")}</p><OnlineRating score="8.0/10" source="Douban" href="https://book.douban.com/subject/37001305/"/><blockquote>{tr(language,"Exploring how information networks have shaped human societies—and what changes when AI joins the network.","探索信息网络如何塑造人类社会，以及当 AI 加入网络后会发生什么。")}</blockquote></div></section><section className="book-addition"><Image className="book-cover-image" src={alchemistBookImage} alt={tr(language,"The Alchemist book cover","《牧羊少年奇幻之旅》封面")} width={320} height={430}/><div className="book-addition-copy"><p className="page-pill">{tr(language,"Recently finished","最近读完")}</p><h3>{tr(language,"The Alchemist","牧羊少年奇幻之旅")}</h3><p className="book-author">{tr(language,"Paulo Coelho","Paulo Coelho · 保羅・科爾賀")}</p><blockquote>{tr(language,"A reminder to stay curious, follow the journey, and notice what the road is trying to teach you.","提醒自己保持好奇、享受旅程，并留意一路上的启示。")}</blockquote><OnlineRating score="8.8/10" source="Douban" href="https://book.douban.com/subject/1345112/"/></div></section></div>}

function Fun({language}:{language:Language}){return <div className="window-page fun-page"><div className="fun-heading"><p className="page-pill">{tr(language,"Off the clock","下班之后")}</p><h2>{tr(language,"Just for Fun","兴趣时光")}</h2><p>{tr(language,"When I’m not architecting data pipelines, I’m usually at the potter’s wheel or exploring digital realms.","不设计数据管道的时候，我通常在陶艺转盘前，或探索数字世界。")}</p></div><div className="fun-grid"><section className="pottery-window"><h3>pottery.studio</h3><div className="pottery-images"><Image src={potteryOneImage} alt="Handmade pottery in progress" width={400} height={280}/><Image src={potteryTwoImage} alt="Colourful glazed pottery" width={400} height={280}/><Image src={potteryThreeImage} alt="Freshly shaped ceramic spoons" width={800} height={360}/></div><div className="mini-tags"><span>{tr(language,"Wheel throwing","拉坯")}</span><span>{tr(language,"Glazing","上釉")}</span></div></section><section className="games-window"><h3>fun.bin</h3><div className="game-card game-card-link"><Image src={splitFictionImage} alt="Split Fiction game cover" width={60} height={60}/><span><b>Split Fiction</b><small>{tr(language,"Sci-fi meets fantasy co-op","科幻与奇幻交织的合作冒险")}</small><OnlineRating compact score="9.1/10" source="Metacritic" href="https://www.metacritic.com/game/split-fiction/"/></span><a href="https://www.ea.com/en/games/split-fiction/split-fiction" target="_blank" rel="noreferrer" aria-label="Visit the official Split Fiction website"><ExternalLink size={15}/></a></div><GameCard image={itTakesTwoImage} title="It Takes Two" note={tr(language,"Co-op masterpiece","合作游戏佳作")} score="8.8/10" ratingHref="https://www.metacritic.com/game/it-takes-two/"/><GameCard image={hogwartsLegacyImage} title="Hogwarts Legacy" note={tr(language,"Magical explorer","魔法世界探索")} score="8.4/10" ratingHref="https://www.metacritic.com/game/hogwarts-legacy/"/><blockquote>{tr(language,"Games are another form of problem solving—just with better graphics than a terminal.","游戏也是解决问题的一种方式，只是画面比终端更精彩。")}</blockquote><button>{tr(language,"Play next quest","开启下一段冒险")}</button></section><section className="conference-window"><div className="conference-mark"><PartyPopper/></div><div><p className="page-pill">{tr(language,"Gaming festival","游戏节")}</p><h3>PAX Aus 2026</h3><p>{tr(language,"Three days of games, live experiences, tournaments, panels, and community at Australia’s biggest celebration of gaming culture.","澳大利亚规模最大的游戏文化盛会，带来三天的游戏体验、赛事、论坛与社区活动。")}</p><div className="conference-meta"><span><CalendarDays/>9&ndash;11 October 2026</span><span><MapPin/>MCEC, Melbourne</span></div></div><a href="https://aus.paxsite.com/" target="_blank" rel="noreferrer">{tr(language,"Visit PAX Aus","访问 PAX Aus")} <ExternalLink size={15}/></a></section><TravelMap language={language}/></div></div>}

function TravelMap({language}:{language:Language}){return <section className="travel-window"><div className="travel-heading"><span className="travel-icon"><Plane/></span><div><p className="page-pill">{tr(language,"Travel map","旅行地图")}</p><h3>{tr(language,"Places explored so far","我们一起走过的地方")}</h3><p>{tr(language,"A growing map of favourite journeys across the Asia–Pacific.","一张持续更新的亚太旅行足迹地图。")}</p></div></div><div className="travel-map" role="img" aria-label={tr(language,"Map showing travels to China, Bali, Australia and New Zealand","显示中国、巴厘岛、澳大利亚和新西兰旅行足迹的地图")}><svg viewBox="0 0 800 440" aria-hidden="true"><path className="map-land" d="M250 55l85-20 100 24 74 54-24 62-87 10-55 67-93-27-48-69z"/><path className="map-land" d="M475 300l83-34 92 38 31 65-51 50-105-20-53-54z"/><path className="map-land" d="M709 353l22-12 13 31-18 42-17-8 11-28z"/><path className="map-island" d="M438 277l54 5 17 14-68 5z"/><path className="map-route" d="M403 148Q480 222 468 288T574 355Q651 391 723 378"/><g className="map-pin china"><circle cx="403" cy="148" r="9"/><text x="419" y="153">{tr(language,"China","中国")}</text></g><g className="map-pin bali"><circle cx="468" cy="288" r="9"/><text x="484" y="293">Bali</text></g><g className="map-pin australia"><circle cx="574" cy="355" r="9"/><text x="590" y="360">{tr(language,"Australia","澳大利亚")}</text></g><g className="map-pin nz"><circle cx="723" cy="378" r="9"/><text x="688" y="410">{tr(language,"New Zealand","新西兰")}</text></g></svg></div><div className="travel-places"><article><MapPinned/><b>{tr(language,"China","中国")}</b><p>{tr(language,"Shanghai · Beijing · Xuzhou · Nanjing · Fuzhou · Quanzhou · Xiamen · Zhangzhou","上海 · 北京 · 徐州 · 南京 · 福州 · 泉州 · 厦门 · 漳州")}</p></article><article><MapPinned/><b>{tr(language,"Australia","澳大利亚")}</b><p>{tr(language,"Melbourne · Sydney · Brisbane","墨尔本 · 悉尼 · 布里斯班")}</p></article><article><MapPinned/><b>{tr(language,"New Zealand","新西兰")}</b><p>{tr(language,"Queenstown","皇后镇")}</p></article><article><MapPinned/><b>Bali</b><p>{tr(language,"Island escape","海岛假期")}</p></article></div></section>}

function GameCard({image,title,note,score,ratingHref}:{image:StaticImageData;title:string;note:string;score:string;ratingHref:string}){return <div className="game-card"><Image src={image} alt="" width={72} height={72}/><span><b>{title}</b><small>{note}</small><OnlineRating compact score={score} source="Metacritic" href={ratingHref}/></span></div>}

function OnlineRating({score,source,href,compact=false}:{score:string;source:string;href:string;compact?:boolean}){return <a className={`online-rating ${compact?"compact":""}`} href={href} target="_blank" rel="noreferrer" aria-label={`${score} on ${source}`}><Star size={14}/><b>{score}</b><span>{source}</span><ExternalLink size={11}/></a>}

function Contact({language}:{language:Language}){return <div className="window-page contact-page"><div className="contact-grid"><article><LinkIcon/><h3>LinkedIn</h3><p>{tr(language,"Professional journey, community work, and engineering updates.","职业经历、社区工作和工程动态。")}</p><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">{tr(language,"Visit profile","访问主页")} <ExternalLink size={15}/></a></article></div><p className="availability"><MapPin size={15}/> {tr(language,"Melbourne · Available for thoughtful collaborations","墨尔本 · 期待有意义的合作")}</p></div>}

function windowTitle(section:DesktopSection){return({overview:"sunshine.exe",about:"about_me.md",work:"data_lover.zip",community:"community.makeaipractical.com",books:"library.db",fun:"personal_atelier.app",contact:"connect.exe"})[section]}










